server:
  extraEnvironmentVars:
    VAULT_ADDR: https://localhost:8200
    VAULT_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  extraVolumes:
    - type: secret
      name: vault-certs
      path: null # /vault/userconfig
  standalone:
    enabled: false
  ha:
    enabled: true
    config:
      listener "tcp" {
        tls_disable = 0
        tls_cert_file = "/vault/userconfig/vault-certs/tls.crt"
        tls_key_file  = "/vault/userconfig/vault-certs/tls.key"
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }
#      seal "gcpckms" {
#         project    = "infra-"
#         region     = "europe-west1"
#         key_ring   = "vault-unseal-keyring"
#         crypto_key = "vault-unseal-key"
#      }
ui:
  enabled: true
  serviceType: "LoadBalancer"
