apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: example-issuer
spec:
  acme:
    email: xundero.k8s@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
#    - dns01:
#        clouddns:
#          project: infra-
#          serviceAccountSecretRef:
#            name: clouddns-dns01-solver-svc-acct
#            key: key.json
    - http01:
        ingress:
          class: nginx
#      selector:
#        matchLabels:
#          "use-http01-solver": "true"
