helmDefaults:
  wait: true
  createNamespace: true
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io
releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    chart:  stable/nginx-ingress
    version: 1.11.1
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.15.1
    set:
      - name: ingressShim.defaultIssuerName
        value: example-issuer
      - name: ingressShim.defaultIssuerKind
        value: ClusterIssuer
      - name: ingressShim.defaultIssuerGroup
        value: cert-manager.io
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.1.2
    values:
      - "../harbor/values.yaml"
