---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    version: "1.0"
spec:
  volumes:
  -
    name: app
    emptyDir: {}
  containers:
  -
    name: web
    image: xunder/testweb:1.0
    readinessProbe:
      httpGet:
        path: "/index.html"
        port: 80
    livenessProbe:
      tcpSocket: { port: 8000 }
    volumeMounts:
    -
      name: app
      mountPath: /app
  initContainers:
  -
    name: index
    image: busybox:1.31
    volumeMounts:
    -
      name: app
      mountPath: /app
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
